# SPDX-License-Identifier: 0BSD

name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  OpenBSD-test:
    runs-on: ubuntu-latest
    name: Test xz on OpenBSD
    steps:
    - uses: actions/checkout@v4.1.6
    - name: Test in OpenBSD
      id: test
      uses: vmactions/OpenBSD-vm@ebafa4eac4adf5e7d04e5bbb4aa764b75dd160df #v1.1.2
      with:
        usesh: true
        prepare: |
          /usr/sbin/pkg_add -I -v autoconf-2.71 automake-1.16.5 gmake gettext-tools gtar libtool m4
        run: |
          set -e
          export LC_ALL=C LANG=C
          export AUTOCONF_VERSION=2.71
          export AUTOMAKE_VERSION=1.16
          uname -a
          # OpenBSD ports lack po4a
          ./autogen.sh --no-po4a
          ./configure --enable-werror
          make
          make check VERBOSE=1
