# SPDX-License-Identifier: 0BSD

name: Solaris

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  solaris-test:
    runs-on: ubuntu-latest
    name: Test xz on Solaris
    steps:
    - uses: actions/checkout@v4.1.6
    - name: Test in Solaris
      id: test
      uses: vmactions/solaris-vm@960d7483ffd6ac03397964cf6423a2f41332c9c8 #v1.0.9
      with:
        usesh: true
        prepare: |
          pkg install bash libtool automake gnu-m4 tree wget gcc autoconf //solaris/text/gawk pkg://solaris/text/gnu-diffutils pkg://solaris/text/gnu-grep pkg://solaris/text/gnu-sed
        run: |
          set -e
          export LC_ALL=C LANG=C
          uname -a
          ./autogen.sh --no-po4a
          ./configure --enable-werror
          make
          make check VERBOSE=1
